Update to new backup logic and use new images

diff --git a/masternode_pod.yaml b/masternode_pod.yaml
--- a/masternode_pod.yaml
+++ b/masternode_pod.yaml
@@ -2,6 +2,8 @@ apiVersion: v1
 kind: Pod
 metadata:
   name: masternode
+  labels:
+    microstream.one/cluster-component: masternode
 spec:
   imagePullSecrets: [ name: microstream-ocir-credentials ]
   securityContext:
@@ -10,47 +12,16 @@ spec:
     fsGroup: 10000
     runAsUser: 10000
     runAsGroup: 10000
+  resources:
+    requests:
+      memory: 2000M
+      cpu: 1000m
+    limits:
+      memory: 2000M
+      cpu: 1000m
   initContainers:
   - name: prepare-masternode
     image: curlimages/curl:8.11.1
-    command: 
-    - sh
-    - -ce
-    - |
-      # Wait for the user rest service project to exist
-      # You can upload the jar like this:
-      # `kubectl cp -c prepare-masternode /path/to/jar masternode:/storage/project/project.jar`
-      # If you have a libs folder as well you can copy it with
-      # `kubectl cp -c prepare-masternode /path/to/libs masternode:/storage/project`
-      # When you are done create the ready flag with
-      # `kubectl exec -ti -c prepare-masternode pod/masternode -- touch /storage/project/ready`
-      mkdir -p /storage/project
-      echo "Waiting for user rest service jar (timeout=10min)..."
-      i=0
-      until [ -f /storage/project/ready ]; do
-        sleep 1s
-        # Fail if we time out
-        if [ $i -gt 600 ]; then
-          echo "Timed out waiting for /storage/project/ready to exist" >&2
-          exit 1
-        fi
-        i=$((i+1))
-      done
-      echo "Success!"
-
-      # Check for kafka ready flag for 5 minutes
-      echo "Waiting for kafka to be ready (timeout=5min)..."
-      i=0
-      until nc -z -w5 kafka 9092; do
-        sleep 1s
-        # Fail if we time out
-        if [ $i -gt 300 ]; then
-          echo "Timed out waiting for kafka to be ready" >&2
-          exit 1
-        fi
-        i=$((i+1))
-      done
-      echo "Success!"
     securityContext:
       allowPrivilegeEscalation: false
       capabilities:
@@ -58,11 +29,81 @@ spec:
     volumeMounts:
     - name: storage
       mountPath: /storage
+    - name: app
+      mountPath: /app
+    resources:
+      requests:
+        memory: 2000M
+        cpu: 1000m
+      limits:
+        memory: 2000M
+        cpu: 1000m
+    command: 
+    - sh
+    - -ce
+    - |
+      # You can upload the jar like this:
+      # `kubectl cp -c prepare-masternode /path/to/jar masternode:/app/application.jar`
+      # If you have a libs folder as well you can copy it with
+      # `kubectl cp -c prepare-masternode /path/to/libs masternode:/app`
+      # When you are done create the ready flag with
+      # `kubectl exec -ti -c prepare-masternode pod/masternode -- touch /app/ready`
+
+      # Wait for the user application to exist
+      if [ ! -f /app/ready ]; then
+        echo "Waiting for /app/ready flag..."
+        while [ ! -f /app/ready ]; do sleep 1; done
+        echo "...done!"
+      fi
+
+      # Wait for kafka
+      if ! nc -z -w5 kafka 9092; then
+        echo "Waiting for kafka..."
+        until nc -z -w5 kafka 9092; do sleep 1; done
+        echo "...done!"
+      fi
   containers:
   - name: masternode
-    image: ocir.microstream.one/onprem/image/microstream-cluster-storage-node:1.14.0-SNAPSHOT
+    image: ocir.microstream.one/onprem/image/microstream-cluster-storage-node:1.14.0
     workingDir: /storage
-    args: [ "/storage/project/project.jar" ]
+    args: [ "/app/application.jar" ]
+    ports:
+    - name: http
+      containerPort: 8080
+    # Restart the pod if container is not responsive at all
+    livenessProbe:
+      periodSeconds: 10
+      timeoutSeconds: 20
+      failureThreshold: 2
+      httpGet:
+        path: /microstream-cluster-controller/microstream-health
+        port: http
+    # Remove the pod from being ready if we fail to check
+    readinessProbe:
+      periodSeconds: 10
+      timeoutSeconds: 20
+      failureThreshold: 1
+      httpGet:
+        path: /microstream-cluster-controller/microstream-health/ready
+        port: http
+    securityContext:
+      allowPrivilegeEscalation: false
+      capabilities:
+        drop: [ all ]
+    volumeMounts:
+    - name: storage
+      mountPath: /storage
+    - name: backups
+      mountPath: /backups
+    - name: app
+      mountPath: /app
+    resources:
+      requests:
+        memory: 2000M
+        cpu: 1000m
+      limits:
+        memory: 2000M
+        cpu: 1000m
     env:
     - name: MSCNL_PROD_MODE
       value: "true"
@@ -81,40 +122,17 @@ spec:
       value: "true"
     - name: IS_BACKUP_NODE
       value: "true"
+    - name: KEPT_BACKUPS_COUNT
+      value: "3"
     - name: BACKUP_PROXY_SERVICE_URL
       value: external-resource-proxy
-    ports:
-    - name: http
-      containerPort: 8080
-    # Restart the pod if container is not responsive at all
-    livenessProbe:
-      timeoutSeconds: 5
-      failureThreshold: 5
-      httpGet:
-        path: /microstream-cluster-controller/microstream-health
-        port: http
-    # Remove the pod from being ready if we fail to check
-    readinessProbe:
-      timeoutSeconds: 4
-      failureThreshold: 3
-      httpGet:
-        path: /microstream-cluster-controller/microstream-health/ready
-        port: http
-    # Give the container ~50 seconds to fully start up
-    startupProbe:
-      timeoutSeconds: 5
-      failureThreshold: 10
-      httpGet:
-          path: /microstream-cluster-controller/microstream-health
-          port: http
-    securityContext:
-      allowPrivilegeEscalation: false
-      capabilities:
-        drop: [ all ]
-    volumeMounts:
-    - name: storage
-      mountPath: /storage
   volumes:
   - name: storage
     persistentVolumeClaim:
       claimName: masternode-storage
+  - name: backups
+    persistentVolumeClaim:
+      claimName: storage-backups
+  - name: app
+    persistentVolumeClaim:
+      claimName: user-app
